### ISSUE TITLE
Windows terminal width is not always 80 chars

### ISSUE THREAD

**Issue by stof** [sebastianbergmann/environment#10]
The `cmd` shell is indeed 80 chars by default. But this does not mean it is always the case:
- you can change the size of `cmd` (not user-friendly as it is not about resizing the window, but possible)
- there is many better terminals for windows, which support arbitrary width.

See https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Application.php#L779-L788 for a logic determining it when possible (using 79 as fallback is still a sensible default though)

**Comment by sebastianbergmann** [comment]
Great! Thanks, @stof.
