### ISSUE TITLE
PHP_BINARY can be empty string

### ISSUE THREAD

**Issue by rvanvelzen** [sebastianbergmann/environment#12]
When running phpunit through arcanist using `@runTestsInSeparateProcesses`, `PHP_BINARY` is `''` leading to $runtime->getBinary() returning `''` as well.

**Comment by rvanvelzen** [comment]
To reproduce:

```php
<?php
$proc = proc_open(
    'php -r "var_dump(PHP_BINARY);"',
    [['pipe', 'r'], ['pipe', 'w']],
    $pipes,
    null,
    []
);

fclose($pipes[0]);

echo stream_get_contents($pipes[1]) . PHP_EOL;
```

(The key here is that an empty env is used, of course)

**Comment by sebastianbergmann** [comment]
See https://github.com/sebastianbergmann/environment/pull/13#issuecomment-179849990 for why I closed this.
