### ISSUE TITLE
Implement equivalent of PHP_OS_FAMILY (for PHP < 7.2)

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/environment#21]
Below is the code used in PHP >= 7.2 to define the `PHP_OS_FAMILY` constant:
```c
#ifdef PHP_WIN32
# define PHP_OS_FAMILY			"Windows"
#elif defined(BSD) || defined(__DragonFly__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__)
# define PHP_OS_FAMILY			"BSD"
#elif defined(__APPLE__) || defined(__MACH__)
# define PHP_OS_FAMILY			"OSX"
#elif defined(__sun__)
# define PHP_OS_FAMILY			"Solaris"
#elif defined(__linux__)
# define PHP_OS_FAMILY			"Linux"
#else
# define PHP_OS_FAMILY			"Unknown"
#endif
```
It would be great if this component had a method that returns the string that would be in `PHP_OS_FAMILY` on >= PHP 7.2 for versions of PHP < 7.2.

In order to implement this based on `PHP_OS`, I need to know the output of
```
$ php -r 'var_dump(PHP_OS);'
```
run on the following operating systems:
- [X] Windows (various (currently supported) versions)
- [X] DragonFly BSD
- [X] FreeBSD
- [X] NetBSD
- [X] OpenBSD
- [X] macOS X
- [X] Solaris
- [X] Linux

**Comment by Rias500** [comment]
macOS X: "Darwin"

**Comment by voda** [comment]
`string(5) "Linux"`

**Comment by galvao** [comment]
Fedora (and I suspect any distro really): 
string(5) "Linux"

**Comment by m-takagi** [comment]
Microsoft Windows 7 SP1 (Microsoft Windows [Version 6.1.7601]): `string(5) "WINNT"`

**Comment by Tjoosten** [comment]
Windows 10: string(5) "WINNT"

**Comment by tobiasgies** [comment]
Ubuntu 16.04, confirming @galvao's suspicion:
string(5) "Linux"

**Comment by JulienItard** [comment]
Linux Mint 18.1
string(5) "Linux"

**Comment by dshafik** [comment]
macOS 10.12: `string(6) "Darwin"`

**Comment by ellotheth** [comment]
Debian 7 (wheezy):
```
string(5) "Linux"
```

**Comment by Slamdunk** [comment]
`string(5) "Linux"` on Slackware 14.0

**Comment by Slamdunk** [comment]
`string(5) "WINNT"` on Windows 7 SP1 & Cygwin

**Comment by s7eph4n** [comment]
`string(5) "Linux"` on RHEL 6.7

**Comment by mgocobachi** [comment]
OSX 10.12: 
string(6) "Darwin"

**Comment by derickr** [comment]
php -r 'var_dump(PHP_OS);'
string(7) "FreeBSD"

```
FreeBSD pledge 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: 
                   Fri Mar 25 02:10:02 UTC 2016     
                   root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  
                   amd64
```

**Comment by sea-wave** [comment]
string(6) "NetBSD"

`NetBSD sdf 7.0.1_PATCH NetBSD 7.0.1_PATCH (GENERIC.201607220540Z) amd64`

**Comment by Ichabond** [comment]
`string(7) "OpenBSD"`
`OpenBSD viper GENERIC.MP#20 amd64`

**Comment by Ichabond** [comment]
After a lot of cursing, shouting, and just general misery:
`string(5) "SunOS"`
`SunOS ranger 5.11 omnios-r151022-f9693432c2 i86pc i386 i86pc`

**Comment by eclipxe13** [comment]
This is the response from a pfSense running FreeBSD
```
# uname -a
FreeBSD the-host-name 10.3-RELEASE-p9 FreeBSD 10.3-RELEASE-p9 #1 5fc1b19(RELENG_2_3_2): Tue Sep 27 12:26:06 CDT 2016     root@ce23-amd64-builder:/builder/pfsense-232/tmp/obj/builder/pfsense-232/tmp/FreeBSD-src/sys/pfSense  amd64

# php -r 'var_dump(PHP_OS);'
Command line code:1:
string(7) "FreeBSD"
```

**Comment by eclipxe13** [comment]
WIP: installing a dragonfly on virtualbox...

**Comment by eclipxe13** [comment]
WIP: installing solaris on virtualbox...

**Comment by werdlv** [comment]
macOS X: `Darwin`
