### ISSUE TITLE
Test against HHVM

### ISSUE THREAD

**Issue by fredemmott** [sebastianbergmann/environment#22]
On travis, currently requires docker - example: https://github.com/facebook/xhp-lib/blob/master/.travis.yml https://github.com/facebook/xhp-lib/blob/master/.travis.sh

Should support 3.20.2+

I understand why you've generally stopped testing most of your projects against HHVM, however given the purpose of this project, it seems likely to be worth an exception.

**Comment by sebastianbergmann** [comment]
If you send a pull request that implements this then I'll merge it.
