### ISSUE TITLE
Failed test: testCanDetectColorSupport

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/environment#5]
When running an automated build

    PHPUnit 4.3.1 by Sebastian Bergmann.
    Configuration read from /builddir/build/BUILD/environment-6288ebbf6fa3ed2b2ff2d69c356fbaaf4f0971a7/phpunit.xml.dist
    F.........
    Time: 14 ms, Memory: 3.00Mb
    There was 1 failure:
    1) SebastianBergmann\Environment\ConsoleTest::testCanDetectColorSupport
    Failed asserting that false is true.

Of course...  (not a tty...)

Proposal: add a "@Group tty" so this test can be easily ignored using --exclude-group=tty

**Comment by stof** [comment]
This should be closed as the assertion was changed in https://github.com/sebastianbergmann/environment/commit/0d9bf79554d2a999da194a60416c15cf461eb67d
