### ISSUE TITLE
stty commands get run in githook where no tty is available

### ISSUE THREAD

**Issue by SunflowerFuchs** [sebastianbergmann/environment#55]
Background is the problem I already reported in sebastianbergmann/phpunit#4029.

`isInteractive` returns true in git hooks thanks to this check:
https://github.com/sebastianbergmann/environment/blob/fff9ba604ff0416ef87bd6eb1fe83f4f6cb52fea/src/Console.php#L93-L95

This means `getNumberOfColumns` will continue to call `getNumberOfColumnsInteractive`, but due to no actual tty being attached, both stty calls fail with an error.

(P.s. I found [this old comment](https://github.com/sebastianbergmann/environment/commit/0d9bf79554d2a999da194a60416c15cf461eb67d#r8258283) with the exact same problem, but that one got initially fixed by that exact isInteractive call haha)

**Comment by GuillaumeSeren** [comment]
Hey,
I stepped into this issue myself, while working on the enabling the tests of phpunit.
So it is a degraded privilege envirronment (gentoo) here are the issue, I get:

```
stty: 'standard input': Inappropriate ioctl for device
```

So after checking the source, I found a workaround by checking if the fstat function is available.

So I have openned a PR with that fix, please review when able :coffee: 

Thank you @sebastianbergmann for this project.
