### ISSUE TITLE
Overridden ini values are ignored when php.ini uses section headers

### ISSUE THREAD

**Issue by Emosewaj** [sebastianbergmann/environment#60]
As of right now, `Runtime::getCurrentSettings()` parses php.ini files respecting section headers using the optional `$process_sections` parameter of `parse_ini_file()`, however, these section headers are then later ignored when comparing the ini file's values to the value retrieved by `ini_get()`. This erroneously causes some ini values that have been overridden via the command line to be ignored and don't get passed through if they either don't exist in the ini file or are under a section header:

```ini
; php.ini
[xdebug]
xdebug.mode=debug
```

`$config = parse_ini_file($ini, true)` results in 
```
array(1) {
  'xdebug' =>
  array(1) {
    'xdebug.mode' =>
    string(5) "debug"
  }
}
```

`$config = parse_ini_file($ini)` results in
```
array(1) {
  'xdebug.mode' =>
  string(5) "debug"
}
```

Additionally, I believe 
`if (isset($config[$value]) && $set != $config[$value])`
should be changed to
`if (!isset($config[$value]) || $set != $config[$value])`
as otherwise, values not set in php.ini but set through the command line would also not be passed through.

**Comment by sebastianbergmann** [comment]
Was this fixed by https://github.com/sebastianbergmann/environment/pull/63?

**Comment by Emosewaj** [comment]
It was, I'm no longer encountering this issue on 5.1.4.
